FROM node:14-alpine
ADD . /appDir
WORKDIR /appDir
CMD ["npm", "start"]
EXPOSE 4000
# 8080 ha ezen fut a backend, a DigitalOcean alapértelmezett beállítása ez

#Akármit akarunk deployolni, dockerrel egyszerű lesz. De ehhez kell egy dockerfile. Expresses nodejs-hez